-- FitScroll synced bank.
--
-- The bank is stored as an append-only event log rather than as a balance.
--
-- Two reasons. First, devices go offline: the Android drain charges a second
-- per second and cannot wait on a network round trip, so each device has to be
-- able to record what it did and reconcile later. A log merges cleanly under
-- that; a "current balance" column would silently lose whichever device wrote
-- second. Second, an append-only log cannot be destroyed by signing out -
-- there is deliberately no delete policy below, so logout can only ever clear
-- the local cache while the ledger itself survives on the server.
--
-- The balance is a deterministic fold over the log: replay events in
-- occurred_at order, applying the same earn/spend/expiry rules the clients use.
-- Every device folding the same events lands on the same number.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- the ledger

create table if not exists public.bank_events (
  -- Generated by the client. Re-uploading an event that already landed is a
  -- primary key conflict rather than a duplicate, which is what makes retries
  -- over a flaky connection safe.
  id uuid primary key,

  user_id uuid not null references auth.users (id) on delete cascade,

  kind text not null check (kind in ('earn', 'spend')),

  -- Earn: seconds minted by completed push-ups. Spend: seconds of screen time
  -- consumed. Always positive; the kind carries the direction.
  seconds integer not null check (seconds > 0 and seconds <= 86400),

  -- When it happened on the device, not when it reached us. Expiry is anchored
  -- to this, so a device that was offline for an hour does not get an hour of
  -- extra shelf life on the minutes it earned.
  occurred_at timestamptz not null,

  device_label text,

  created_at timestamptz not null default now()
);

-- Clients only ever ask for the last day or so of events, newest first.
create index if not exists bank_events_user_time
  on public.bank_events (user_id, occurred_at desc);

alter table public.bank_events enable row level security;

create policy "read own events"
  on public.bank_events
  for select
  using (auth.uid() = user_id);

create policy "append own events"
  on public.bank_events
  for insert
  with check (
    auth.uid() = user_id
    -- Expiry is driven by occurred_at, so a timestamp in the future would be a
    -- way to mint minutes that never run out. A few minutes of slack absorbs
    -- ordinary clock skew; anything beyond that is rejected.
    and occurred_at <= now() + interval '5 minutes'
    and occurred_at >= now() - interval '30 days'
  );

-- No update policy and no delete policy, on purpose. The ledger is append-only:
-- events cannot be edited or removed by a client, which is what guarantees a
-- bank survives signing out, reinstalling, or switching devices.

-- ------------------------------------------------------------- user settings

create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  strictness smallint not null default 3 check (strictness between 1 and 5),
  bank_cap_minutes integer not null default 1440
    check (bank_cap_minutes between 15 and 1440),
  warn_before_lock boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "read own profile"
  on public.profiles for select using (auth.uid() = user_id);

create policy "create own profile"
  on public.profiles for insert with check (auth.uid() = user_id);

create policy "update own profile"
  on public.profiles for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Give every new account a profile row so clients never have to special-case a
-- missing one on first sign-in.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ------------------------------------------------------------------ pruning
--
-- Every minute expires 24 hours after it was earned, so nothing older than
-- that can affect a balance. Clients already query a 25 hour window; this is
-- for keeping the table small, and is safe to schedule daily via pg_cron or to
-- never run at all.

create or replace function public.prune_bank_events()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed integer;
begin
  delete from public.bank_events
  where occurred_at < now() - interval '7 days';
  get diagnostics removed = row_count;
  return removed;
end;
$$;
